### ISSUE TITLE
Can't run iOS app on iPad.

### ISSUE THREAD

**Issue by pkclsoft** [manavgabhawala/CocoaMultipeer#2]
When I attempt to run the iOS app on an iPad I get the following:

MultipeerCocoaiOS/MGBrowserTableViewController.swift: 17: 22: fatal error: use of unimplemented initializer 'init(nibName:bundle:)' for class 'MultipeerCocoaiOS.MGBrowserTableViewController'

**Comment by manavgabhawala** [comment]
It runs fine on both the iPad and iPhone in the Demo iOS app. Check that for a how to use. In general, using it in a storyboard requires you to use MultipeerCocoaiOS.MGBrowserViewController see the header doc of that class for more information

**Comment by pkclsoft** [comment]
Its the demo app that I'm running.

**Comment by pkclsoft** [comment]
OK, so the problem only occurs if you run it on a device running iOS 8.4 or earlier.  My iOS 9 iPhone is fine, as are the 9.0 simulators.  This is all on clean, unaltered code.
